services:
  ckan:
    labels:
      - "autoheal=true"
    healthcheck:
      test: wget --no-verbose --timeout=10 --tries=1 --spider http://localhost:5000/ || exit
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
  ssl:
    image: nginx
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /srv/nginx/key.pem:/root/ssl/key.pem
      - /srv/nginx/cert.pem:/root/ssl/cert.pem
    depends_on:
      - ckan
    ports:
      - "443:443"
      - "80:80"
  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: "15"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: none
